(require 'server)
(unless (server-running-p)
  (server-start))
(setq server-log t)

(setq kec:config-dir
      (file-name-directory (file-truename load-file-name)))
(add-to-list 'load-path kec:config-dir)

(load "custom")

(load "lisp-utils")
(load "log")
(load "general-utils")
(load "insert")
(load "convert")
(load "windmove-extra")
(load "term")
(load "konsole")
(load "easy-window-split")
(load "key-overrides")
(load "ido")
(load "diff")
(load "record-keys")
(load "keymaps")
(load "go-mod")
(load "recent-keys")
(load "sexp-traverse")
(load "requote")

(load "modes")
(load "minor-modes")
(load "isearch")
(load "lisp-modes")
(load "vars")
(load "faces")
(load "hooks")
(load "keymaps")
(load "c")
(load "comint")
(load "ielm")
(load "ido")
(load "js")
(load "makefile")
(load "sh")
(load "debug")
(load "temp-files")
(load "smerge")
(load "flymake")
(load "ibuffer")
(load "after-init")
