(setq term-bind-key-alist (quote (("C-c C-c" . term-interrupt-subjob)
                                  ("C-p" . previous-line)
                                  ("C-n" . next-line)
                                  ("C-c C-s" . isearch-forward)
                                  ("C-c C-r" . isearch-backward)
                                  ("C-m" . term-send-raw)
                                  ("C-_" . term-send-raw)
                                  ("M-f" . term-send-forward-word)
                                  ("M-<right>" . term-send-forward-word)
                                  ("C-<right>" . term-send-forward-word)
                                  ("M-b" . term-send-backward-word)
                                  ("M-<left>" . term-send-backward-word)
                                  ("C-<left>" . term-send-backward-word)
                                  ("M-o" . term-send-backspace)
                                  ("M-p" . term-send-up)
                                  ("M-n" . term-send-down)
                                  ("M-M" . term-send-forward-kill-word)
                                  ("M-d" . term-send-forward-kill-word)
                                  ("M-DEL" . term-send-forward-kill-word)
                                  ("C-DEL" . term-send-forward-kill-word)
                                  ("<C-delete>" . term-send-forward-kill-word)
                                  ("M-N" . term-send-backward-kill-word)
                                  ("M-<backspace>" . term-send-backward-kill-word)
                                  ("C-<backspace>" . term-send-backward-kill-word)
                                  ("M-r" . term-send-reverse-search-history)
                                  ("M-," . term-send-input)
                                  ("M-." . comint-dynamic-complete)
                                  ("C-x <next>" . multi-term-next)
                                  ("C-x <prior>" . multi-term-prev))))

(setq term-unbind-key-list '("C-z" "C-q" "C-x" "C-h" "C-c" "M-x" "C-t"))

(defun term-backward-kill-word-custom ()
  "Backward kill word using <C-backspace>-like function, not C-w"
  (interactive)
  (term-send-raw-string "\e\C-?"))

(defun term-mode-customize ()
  (setq-local scroll-margin 0)
  (dolist (key '("<M-left>" "<M-right>"))
    (define-key term-raw-map (kbd key) nil))
  (define-key term-raw-map (kbd "C-r") 'term-send-raw)
  (define-key term-raw-map (kbd "C-s") 'term-send-raw)
  (define-key term-raw-map (kbd "C-c SPC") 'term-line-mode)
  (define-key term-mode-map (kbd "C-c SPC") 'term-char-mode)
  (define-key term-raw-map (kbd "C-w") 'term-backward-kill-word-custom)
  (define-key term-raw-map (kbd "C-<backspace>") 'term-backward-kill-word-custom))

(add-hook 'term-mode-hook 'term-mode-customize)
