(defun c-mode-keymap-modify ()
  (dolist (key '("C-d" "C-c C-d" "C-c C-\\"))
    (eval `(local-unset-key (kbd ,key))))
  (local-unset-key (kbd "C-M-q"))
  (local-set-key (kbd "C-{") 'c-embrace-selected-lines)
  (local-set-key (kbd "C-;") 'c-finalize-string))

(defun c-finalize-string ()
  (interactive)
  (end-of-line)
  (insert ";")
  (funcall (key-binding (kbd "RET"))))

(defun c-embrace-selected-lines ()
  (interactive)
  (let ((oldpoint (point))
        (oldmark (mark))
        (mark-was-set-p (use-region-p))
        (oldsize (buffer-size))
        increment)
    (destructuring-bind (open close) (selected-lines)
      (when (= (char-before close) 10)
        (setq close (1- close)))
      (deactivate-mark)
      (goto-char open)
      (newline-and-indent)
      (previous-line)
      (insert "{")
      (c-indent-line-or-region)
      (setq increment (- (buffer-size) oldsize))
      (goto-char (setq close (+ increment close)))
      (newline-and-indent)
      (insert "}")
      (c-indent-line-or-region)
      (c-indent-region (+ increment open) close))
    (goto-char (+ oldpoint increment))
    (when mark-was-set-p
      (set-mark (+ oldmark increment)))))

(defun c-define-style ()
  (setq c-style-alist (append c-style-alist
                              '(("kevwargo"
                                 (c-basic-offset . 4)
                                 (c-comment-only-line-offset 0 . 0)
                                 (c-offsets-alist
                                  (inline-open . 0)
                                  (statement-block-intro . +)
                                  (substatement-open . 0)
                                  (substatement-label . 0)
                                  (label . 0)
                                  (case-label . +)
                                  (statement-cont . +)))))))

(defun c-mode-for-lex-yacc ()
  (when (string-match-p ".*\\.l$\\|.*\\.y$" (buffer-file-name))
    (scratch-log "using lex and yacc bindings")
    (local-set-key (kbd ";") 'self-insert-command)
    (local-set-key (kbd ":") 'self-insert-command)
    (local-set-key (kbd ",") 'self-insert-command)
    (local-set-key (kbd "(") 'self-insert-command)
    (local-set-key (kbd ")") 'self-insert-command)
    (local-set-key (kbd "{") 'self-insert-command)
    (local-set-key (kbd "}") 'self-insert-command)))
    
    
(add-hook 'c-mode-common-hook 'c-mode-for-lex-yacc)
(add-hook 'c-mode-common-hook 'c-mode-keymap-modify)
(add-hook 'c-initialization-hook 'c-define-style)
