(defun custom-lisp-modes-map ()
  (local-set-key (kbd "C-x J") 'jlp-send-defun)
  (local-set-key (kbd "C-c C-f") 'find-function)
  (local-set-key (kbd "C-x j") (let ((m (make-sparse-keymap)))
                                 (keymap-set m "d" 'jlp-send-defun)
                                 (keymap-set m "s" 'jlp-send-sexp)
                                 (keymap-set m "b" 'jlp-send-buffer)
                                 m)))

(add-hook 'lisp-mode-hook 'custom-lisp-modes-map)
(add-hook 'emacs-lisp-mode-hook 'custom-lisp-modes-map)
