(require 'cl-macs)

(defvar requote-pairs
  '((?\" . ?\")
    (?' . ?')
    (?` . ?`)
    (?< . ?>)
    (?\[ . ?\])
    (?\( . ?\))
    (?{ . ?})))

(defun requote (start end open close)
  (interactive (if (region-active-p)
                   (let ((start (region-beginning))
                         (end (1- (region-end)))
                         open)
                     (if (< (- end start) 1)
                         (user-error "Requote region [%d:%d] is too small" start end)
                       (setq open (read-char-from-minibuffer "Requote with: "))
                       (list start end open (or (cdr-safe (assoc open requote-pairs))
                                                (user-error "Cannot find closing pair for %s"
                                                            (key-description (vector open)))))))
                 (user-error "No active region")))
  (cl-flet ((overwrite (pos newchar)
              (goto-char pos)
              (delete-char 1)
              (insert newchar)))
    (overwrite start open)
    (overwrite end close)))
