(defun custom-lisp-modes-map ()
  (keymap-local-set "C-x J" 'jlp-send-defun)
  (keymap-local-set "C-c C-f" 'find-function)
  (keymap-local-set "C-x j" (let ((m (make-sparse-keymap)))
                              (keymap-set m "d" 'jlp-send-defun)
                              (keymap-set m "s" 'jlp-send-sexp)
                              (keymap-set m "b" 'jlp-send-buffer)
                              m)))

(add-hook 'lisp-mode-hook 'custom-lisp-modes-map)
(add-hook 'emacs-lisp-mode-hook 'custom-lisp-modes-map)
